version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout

      - add_ssh_keys:
        fingerprints:
          - "a7:fd:97:72:21:35:9d:44:00:d7:18:05:69:04:b6:38"

      - run:
        name: Start ssh-keyscan
        command: |
          ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts

      - deploy:
        name: Start master deploy
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            rsync -av --delete --exclude='.git' --exclude='.circleci' ./${USER_NAME}@${HOST_NAME}:/web/observer_release
          fi